/* ==================================== JUCER_BINARY_RESOURCE ====================================

   This is an auto-generated file: Any edits you make may be overwritten!

*/

namespace BinaryData
{

//================== tinyterrorface ==================
static const unsigned char temp_binary_data_1[] =
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n"
"\r\n"
"<magic>\r\n"
"  <Style name=\"default\">\r\n"
"    <Nodes/>\r\n"
"    <Classes>\r\n"
"      <plot-view border=\"2\" background-color=\"black\" border-color=\"silver\" display=\"contents\"/>\r\n"
"      <nomargin margin=\"0\" padding=\"0\" border=\"0\"/>\r\n"
"      <group margin=\"5\" padding=\"5\" border=\"2\" flex-direction=\"column\"/>\r\n"
"      <transparent background-color=\"transparentblack\"/>\r\n"
"    </Classes>\r\n"
"    <Types>\r\n"
"      <Slider border=\"0\" slider-textbox=\"textbox-below\"/>\r\n"
"      <ToggleButton border=\"0\" max-height=\"50\" caption-size=\"0\" text=\"Active\"/>\r\n"
"      <TextButton border=\"0\" max-height=\"50\" caption-size=\"0\"/>\r\n"
"      <ComboBox border=\"0\" max-height=\"50\" caption-size=\"0\"/>\r\n"
"      <Plot border=\"0\" margin=\"0\" padding=\"0\" background-color=\"00000000\"\r\n"
"            radius=\"0\"/>\r\n"
"      <XYDragComponent border=\"0\" margin=\"0\" padding=\"0\" background-color=\"00000000\"\r\n"
"                       radius=\"0\"/>\r\n"
"    </Types>\r\n"
"  </Style>\r\n"
"  <View id=\"root\" resizable=\"0\" resize-corner=\"0\" background-color=\"FF000000\" width=\"1000\" height=\"500\">\r\n"
"    <View class=\"parameters nomargin\" flex-direction=\"column\" background-color=\"FFC27A18\"\r\n"
"          border=\"0\" padding=\"20\">\r\n"
"      <View flex-grow=\"1.7\" lookAndFeel=\"FoleysFinest\" background-color=\"00000000\"\r\n"
"            margin=\"10\" padding=\"\">\r\n"
"        <View padding=\"10\" background-image=\"wood_plate_jpg\" image-placement=\"fill\"\r\n"
"              border=\"15\" radius=\"0\" border-color=\"FFFFFFFF\">\r\n"
"          <Label text=\"Oringi Tiny Terrir\" justification=\"bottom-left\" font-size=\"50\"\r\n"
"                 padding=\"15\" lookAndFeel=\"FoleysFinest\" label-background=\"00000000\"\r\n"
"                 background-color=\"00000000\" label-text=\"FFFFFFFF\" label-outline=\"\"/>\r\n"
"        </View>\r\n"
"      </View>\r\n"
"      <View lookAndFeel=\"FoleysFinest\" margin=\"10\" background-color=\"FFFFFFFF\">\r\n"
"        <View flex-direction=\"row\" flex-grow=\"1.5\" border=\"1\" radius=\"0\" background-color=\"FFB0B0B0\"\r\n"
"              margin=\"0\" padding=\"0\">\r\n"
"          <Slider caption=\"High Pass\" parameter=\"Input high pass\" slider-type=\"rotary-horizontal-vertical\"\r\n"
"                  slider-textbox=\"no-textbox\" rotary-fill=\"FFE29393\" rotary-outline=\"FF7A7A7A\"\r\n"
"                  flex-grow=\"1.0\" caption-placement=\"centred-bottom\" caption-color=\"FFFFFFFF\"\r\n"
"                  background-color=\"00000000\"/>\r\n"
"          <Slider parameter=\"Input Gain\" slider-type=\"rotary-horizontal-vertical\"\r\n"
"                  slider-textbox=\"no-textbox\" class=\"ampcontrol\" caption-placement=\"centred-bottom\"\r\n"
"                  caption-color=\"FFFFFFFF\" lookAndFeel=\"FoleysFinest\" rotary-fill=\"FFE29393\"\r\n"
"                  rotary-outline=\"FF7A7A7A\" background-color=\"00000000\" caption=\"Input Gain\"\r\n"
"                  caption-size=\"20\"/>\r\n"
"          <ComboBox caption=\"Gain Level\" parameter=\"Gain Level\" flex-shrink=\"1.0\"\r\n"
"                    flex-grow=\"1.0\" caption-placement=\"centred-bottom\" background-color=\"00000000\"\r\n"
"                    caption-color=\"FFFFFFFF\"/>\r\n"
"        </View>\r\n"
"        <Slider caption=\"Preamp Gain\" parameter=\"Preamp Gain\" slider-type=\"rotary-horizontal-vertical\"\r\n"
"                class=\"ampcontrol\" caption-size=\"15\" caption-color=\"FF000000\"\r\n"
"                caption-placement=\"centred-bottom\" lookAndFeel=\"Skeuomorphic\"\r\n"
"                slider-textbox=\"no-textbox\" rotary-fill=\"FFE29393\" background-color=\"00000000\"/>\r\n"
"        <Slider caption=\"Shape\" parameter=\"Shape\" slider-type=\"rotary-horizontal-vertical\"\r\n"
"                caption-placement=\"centred-bottom\" slider-textbox=\"no-textbox\"\r\n"
"                lookAndFeel=\"Skeuomorphic\" slider-text=\"\" caption-color=\"FF000000\"\r\n"
"                caption-size=\"15\" rotary-fill=\"FFE29393\" background-color=\"00FFFFFF\"/>\r\n"
"        <Slider caption=\"Master volume\" parameter=\"Master volume\" slider-type=\"rotary-horizontal-vertical\"\r\n"
"                caption-color=\"FF000000\" caption-placement=\"centred-bottom\" slider-textbox=\"no-textbox\"\r\n"
"                lookAndFeel=\"Skeuomorphic\" rotary-fill=\"FFE29393\" caption-size=\"15\"\r\n"
"                background-color=\"00FFFFFF\"/>\r\n"
"        <Slider caption=\"Tube Compression\" parameter=\"Tube Compression\" slider-type=\"inc-dec-buttons\"\r\n"
"                flex-grow=\"0.6\" radius=\"0\" background-color=\"FFB0B0B0\" caption-color=\"FFFFFFFF\"\r\n"
"                caption-placement=\"centred-bottom\"/>\r\n"
"      </View>\r\n"
"    </View>\r\n"
"  </View>\r\n"
"  <Styles>\r\n"
"    <Style name=\"default\">\r\n"
"      <Nodes/>\r\n"
"      <Classes>\r\n"
"        <plot-view border=\"2\" background-color=\"black\" border-color=\"silver\" display=\"contents\"/>\r\n"
"        <nomargin margin=\"0\" padding=\"0\" border=\"0\"/>\r\n"
"        <group margin=\"5\" padding=\"5\" border=\"2\" flex-direction=\"column\"/>\r\n"
"        <transparent background-color=\"transparentblack\"/>\r\n"
"      </Classes>\r\n"
"      <Types>\r\n"
"        <Slider border=\"0\" slider-textbox=\"textbox-below\"/>\r\n"
"        <ToggleButton border=\"0\" max-height=\"50\" caption-size=\"0\" text=\"Active\"/>\r\n"
"        <TextButton border=\"0\" max-height=\"50\" caption-size=\"0\"/>\r\n"
"        <ComboBox border=\"0\" max-height=\"50\" caption-size=\"0\"/>\r\n"
"        <Plot border=\"0\" margin=\"0\" padding=\"0\" background-color=\"00000000\"\r\n"
"              radius=\"0\"/>\r\n"
"        <XYDragComponent border=\"0\" margin=\"0\" padding=\"0\" background-color=\"00000000\"\r\n"
"                         radius=\"0\"/>\r\n"
"      </Types>\r\n"
"      <Palettes>\r\n"
"        <default/>\r\n"
"      </Palettes>\r\n"
"    </Style>\r\n"
"  </Styles>\r\n"
"</magic>\r\n"
"\0";

const char* tinyterrorface = (const char*) temp_binary_data_1;
}
